services:

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEVUSER: ${DEVUSER}
    depends_on:
      - broker
    networks:
      - agent_network
    volumes:
      - ${REPOSDIR}/agent:${WORKSPACEDIR}/agent
      - build_volume:${WORKSPACEDIR}/agent/build
      - ${HOME}/.ssh:/home/${DEVUSER}/.ssh
      - ${HOME}/certs:/workspaces/certs
    command: ["sleep", "infinity"]

  broker:
    image: mathemaphysics/rabbitmq:3-management-ssl
    ports:
      - "15672:15672"
      - "15671:15671"
    volumes:
      - ${HOME}/certs:/etc/rabbitmq/certs
    networks:
      - agent_network
    entrypoint: /usr/local/bin/docker-entrypoint.sh
    command: rabbitmq-server

networks:
  agent_network:

volumes:
  build_volume:

